global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'bullmq'
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ['abyss-agent-testnet.railway.internal']

  # - job_name: 'pgpool'
  #   scheme: https
  #   static_configs:
  #     - targets: ['URL_GOES_HERE']